### ISSUE TITLE
Add Footer folder

### ISSUE THREAD

**Issue by AnirudhPanda** [siddhi-244/Embellish#10]
Footer folder can contain the different styles of footers!

**Comment by AB-Jeet** [comment]
If this for hacktoberfest then Can you pls assign it to me ?

**Comment by siddhi-244** [comment]
You have to add a component but not a folder !

**Comment by AB-Jeet** [comment]
Will do that . One doubt is, what do you mean by different styles ?? What do you aspect from footer styles ??

**Comment by siddhi-244** [comment]
> Will do that . One doubt is, what do you mean by different styles ?? What do you aspect from footer styles ??

Designed components.  You can add footer with good design. Open a new issue for that.
