### ISSUE TITLE
CSS Loading Animations

### ISSUE THREAD

**Issue by WH0SUMIT** [siddhi-244/Embellish#11]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I'd like to add some CSS loaders with some cool and awesome animations.

**Describe alternatives you've considered**

**Additional context**

**Comment by siddhi-244** [comment]
@WH0SUMIT assigning this to you. Make sure you follow the folder structure and add only 1 loader. If you want to add more, create a new issue !

**Comment by WH0SUMIT** [comment]
can I create the same type of loaders in 1 file ??

**Comment by siddhi-244** [comment]
> can I create the same type of loaders in 1 file ??

Choose the best loader and add it in the file

**Comment by WH0SUMIT** [comment]
okay, thank you!
