### ISSUE TITLE
Glassmorphism effect  using Html & Css

### ISSUE THREAD

**Issue by khoseADITI** [siddhi-244/Embellish#110]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
null.

**Describe alternatives you've considered**
null

**Additional context**

https://user-images.githubusercontent.com/89697654/135764179-49a8d723-88a3-47f8-aff3-340ddc0877ea.mp4

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊

**Comment by Bhawna147** [comment]
@siddhi-244 what exactly needs to be done in this issue?
