### ISSUE TITLE
3D Flip Card

### ISSUE THREAD

**Issue by TechSpiritSS** [siddhi-244/Embellish#112]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to contribute a 3D Flip Card into the Cards Folder which flips when hovered upon consisting of all the details at the back side of the card like Link and Info.

**Describe alternatives you've considered**
I will use HTML and CSS along with Font Awesome kit to get the work done

**Additional context**
![image](https://user-images.githubusercontent.com/76687985/135765515-2b3ecb43-b6d1-46a1-9e33-cdc9c8f62e48.png)

**Comment by TechSpiritSS** [comment]
Can you assign this to me?

**Comment by TechSpiritSS** [comment]
![OeMkolCx8v](https://user-images.githubusercontent.com/76687985/135765743-94e88f84-da0a-4d62-92fb-8ced7b70b5f9.gif)

**Comment by siddhi-244** [comment]
I think flip card is already done. Can uh try something else

**Comment by TechSpiritSS** [comment]
Yeah but that was different from this

**Comment by siddhi-244** [comment]
> Yeah but that was different from this

You can try another component
