### ISSUE TITLE
Animated Profile

### ISSUE THREAD

**Issue by TechSpiritSS** [siddhi-244/Embellish#115]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
A profile card which shows info on being hover upon

**Describe alternatives you've considered**
I am using HTML, CSS and Font Awesome to make it happen

**Additional context**
![FeUsH3LVTS](https://user-images.githubusercontent.com/76687985/135766861-e25c8e8a-79a5-4669-a654-2a63739ca3d9.gif)

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊
