### ISSUE TITLE
Shiny Button

### ISSUE THREAD

**Issue by TechSpiritSS** [siddhi-244/Embellish#116]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
On mouse hover a button shines over

**Describe alternatives you've considered**
Basic CSS is being used to make this hover effect

**Additional context**
![HmGg3tI36g](https://user-images.githubusercontent.com/76687985/135767944-6ccde30f-e61c-445d-9134-c408c45d692a.gif)

**Comment by siddhi-244** [comment]
Try something new !
