### ISSUE TITLE
Add CSS Progress Bars 

### ISSUE THREAD

**Issue by WH0SUMIT** [siddhi-244/Embellish#12]
**Is your feature request related to a problem? Please describe.**
NO. this feature request is not related to a problem.

**Describe the solution you'd like**
I'd like to add a custom progress bar with animation. 

**Describe alternatives you've considered**

**Additional context**

**Comment by siddhi-244** [comment]
@WH0SUMIT  assigning this to you. Make a folder called progress bar and follow all the guidelines.  Add only one component.  If you want to add more create a new issue.
