### ISSUE TITLE
A Timeline for events and blog section

### ISSUE THREAD

**Issue by nandini7637** [siddhi-244/Embellish#120]
@siddhi-244 Can I work on this please?

**Comment by siddhi-244** [comment]
Follow issue template and describe it

**Comment by nandini7637** [comment]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.
: Not a problem but I would like to add blogs and timeline section templates for the repo

**Describe the solution you'd like**
For ecommerce websites and porfolio particularly, it's important to include customer reviews and blogs related to their work also a event timeline to show future and past events in the order they occur. These components will be completely responsive. 

**Additional context**
Will include ss Or video.

**Comment by nandini7637** [comment]
> Follow issue template and describe it

Sorry, I have corrected it

**Comment by siddhi-244** [comment]
We don't want templates ,we need components
