### ISSUE TITLE
Custom Preloader

### ISSUE THREAD

**Issue by Asmit2952** [siddhi-244/Embellish#121]
**Is your feature request related to a problem? Please describe.**
Create and implement custom Preloader for your website with HTML, CSS and JS

**Comment by siddhi-244** [comment]
We don't need svg ,we need it in html,css.

**Comment by Asmit2952** [comment]
> We don't need svg ,we need it in html,css.

Okk, I'll do that 👍🏻👍🏻

**Comment by Asmit2952** [comment]
Is this a valid issue? @siddhi-244

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊🎊
