### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by mrudulkolambe** [siddhi-244/Embellish#125]
**Glassmorphism Contact Form**
A well structured contact page, that can be used on any platform. Makes it easier to add on your specific attributes and data
![Screenshot (55)](https://user-images.githubusercontent.com/83169198/135853999-4bb7a4a4-0369-4341-aa87-d0883c6a3959.png)

**Comment by mrudulkolambe** [comment]
A well structured contact page, that can be used on any platform. Makes it easier to add on your specific attributes and data

**Comment by siddhi-244** [comment]
Assigning this to you 🎊🎊🎊🎊🎊🎊
