### ISSUE TITLE
Services Section

### ISSUE THREAD

**Issue by gurupawar** [siddhi-244/Embellish#128]
**Is your feature request related to a problem? Please describe.**
 to add new component

**Describe the solution you'd like**
N/A

**Describe alternatives you've considered**
N/A

**Additional context**
I would like to contribute with some good looking and responsive Services Sections under #hacktoberfest that can be used to any website with just html & css.

**Comment by siddhi-244** [comment]
Describe the component

**Comment by siddhi-244** [comment]
> i will create this kind of services section for websites using html css
> 
> ![2021-10-07 13_28_21-Services section from web (unused element part 8 ) by Prakhar Neel Sharma on Dri](https://user-images.githubusercontent.com/62001513/136343715-de49eacd-6f0d-4fac-b748-69ce05aec55e.png)

You wanna continue?
