### ISSUE TITLE
Add a background (Particles)

### ISSUE THREAD

**Issue by SanskritiKushik5** [siddhi-244/Embellish#13]
**Is your feature request related to a problem? Please describe.**
I would like to add a background.

**Describe the solution you'd like**
Background made with particles.js which is quite popular!

**Describe alternatives you've considered**
Nil

**Additional context**
Nil

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to add a background.
> 
> **Describe the solution you'd like** Background made with particles.js which is quite popular!
> 
> **Describe alternatives you've considered** Nil
> 
> **Additional context** Nil

Assigning this to you. Make sure you follow the instructions! 🎊🎊

**Comment by WH0SUMIT** [comment]
hello @SanskritiKushik5 , I think we have to create designed components in CSS only.

**Comment by siddhi-244** [comment]
> > **Is your feature request related to a problem? Please describe.** I would like to add a background.
> > **Describe the solution you'd like** Background made with particles.js which is quite popular!
> > **Describe alternatives you've considered** Nil
> > **Additional context** Nil
> 
> please try to make it in css

**Comment by siddhi-244** [comment]
> hello @SanskritiKushik5 , I think we have to create designed components in CSS only.

Yes you have to make it in html css and vanilla je only
