### ISSUE TITLE
Modal using html, css and js

### ISSUE THREAD

**Issue by Chaitalishetty** [siddhi-244/Embellish#134]
**Is your feature request related to a problem? Please describe.**
Clicking on the button will trigger a modal

**Additional context**
<video src="https://user-images.githubusercontent.com/66556168/136187377-2927eda9-8b77-424f-bad4-cb59a03e19c7.mp4"></video>

**Comment by siddhi-244** [comment]
Assigning this to you. Make sure you follow folder structure!
