### ISSUE TITLE
Card component with video background on hover (Disney+ style)

### ISSUE THREAD

**Issue by Xelaflash** [siddhi-244/Embellish#135]
**Is your feature request related to a problem? Please describe.**
Hello,
I want to add a component to your project.
Component will be a card with a video playing (background) on hover, like in Disney+ website. 
Not related to any specific issue but just a piece of UI. 

Describe the solution you'd like
A card grid component using HTML, CSS and JS.

Describe alternatives you've considered
N/A

Additional context
Can this be assigned under hacktoberfest pls?

**Comment by siddhi-244** [comment]
Assigning this to you 🎊
