### ISSUE TITLE
Accordion

### ISSUE THREAD

**Issue by WH0SUMIT** [siddhi-244/Embellish#14]
**Is your feature request related to a problem? Please describe.**
No, this feature is not related to any problems.

**Describe the solution you'd like**
want to add an accordion in glassmorphism style.

**Describe alternatives you've considered**
Or I can also create an accordion without glassmorphism style.

**Additional context**

**Comment by siddhi-244** [comment]
@WH0SUMIT . It would be really great if you complete the assigned issues first. I will assign this to you. But next time make sure you complete the first 2 issues and then ask for next.
