### ISSUE TITLE
Animation in Input Box

### ISSUE THREAD

**Issue by ayush-sleeping** [siddhi-244/Embellish#147]
**Describe the solution you'd like**
Here , I am going to show how can you give your input box in your web more modern and animated look

**Additional context**
Using Html and CSS

**Screenshot**
Common Input box:-
![Screenshot (504)](https://user-images.githubusercontent.com/76460132/136496113-2c6fbc07-7008-4a95-ab11-3a8e5706baca.png)

<br>

what I am going to make:-
![Screenshot (505)](https://user-images.githubusercontent.com/76460132/136496218-bee6ebc6-df01-48db-9030-fb22cd53702b.png)

**Comment by ayush-sleeping** [comment]
@siddhi-244 please this issue to me .......

**Comment by siddhi-244** [comment]
We need designed components  !
