### ISSUE TITLE
Add Footer design

### ISSUE THREAD

**Issue by AB-Jeet** [siddhi-244/Embellish#15]
**Is your feature request related to a problem? Please describe.**
Footer Design

**Describe the solution you'd like*
Adding good design to footer.

**Comment by AB-Jeet** [comment]
Pls assign it to me under hacktoberfest.

**Comment by WH0SUMIT** [comment]
footer design is not a component I guess.

**Comment by siddhi-244** [comment]
It's okayy you can add footer designs as well,but make sure it's purely html,css and js.

**Comment by siddhi-244** [comment]
> Pls assign it to me under hacktoberfest.

Assigning this to you. 🎊🎊🎊

**Comment by AB-Jeet** [comment]
Thanks for assigning . I will do it in HTML,CSS, JS only.

**Comment by siddhi-244** [comment]
Any updates ?

**Comment by siddhi-244** [comment]
Sure. All the best !

**Comment by AB-Jeet** [comment]
Pls consider my PR for the issue #15
