### ISSUE TITLE
Dot Loader CSS Animation

### ISSUE THREAD

**Issue by gurupawar** [siddhi-244/Embellish#151]
**Is your feature request related to a problem? Please describe.**
loader animation

**Describe the solution you'd like**
i will create a cool and smooth dot loader animation using css and html.

**Describe alternatives you've considered**

**Additional context**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/62001513/136792010-5ec5726f-338e-4765-8c7c-525cdb5b8774.gif)

**Comment by siddhi-244** [comment]
Assigning 💥💥
