### ISSUE TITLE
Circle Loader CSS Animation 

### ISSUE THREAD

**Issue by jlzaratec** [siddhi-244/Embellish#166]
**Is your feature request related to a problem? Please describe.**
Circle loader animation

**Describe the solution you'd like**
i will create a cool and smooth circle loader animation using css and html.

**Describe alternatives you've considered**

**Additional context**
![Circle loader](https://github.com/jlzaratec/identidad/blob/master/images/circle-loader.gif)

**Comment by siddhi-244** [comment]
Assigning

**Comment by jlzaratec** [comment]
**Hello**, Issue **_has been finalized_** with PR https://github.com/siddhi-244/Embellish/pull/163
