### ISSUE TITLE
Add Background design

### ISSUE THREAD

**Issue by SanskritiKushik5** [siddhi-244/Embellish#17]
**Is your feature request related to a problem? Please describe.**
Background design

**Describe the solution you'd like**
Adding a background with parallax effect.

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Background design
> 
> **Describe the solution you'd like** Adding a background with parallax effect.

Assigning this to you🎊🎊🎊🎊🎊🎊
