### ISSUE TITLE
Add new Scroll Through Image To Change Text Parallax Effect

### ISSUE THREAD

**Issue by Bhaviktutorials** [siddhi-244/Embellish#183]
**Is your feature request related to a problem? Please describe.**
no
**Describe the solution you'd like**
null

**Describe alternatives you've considered**
null

**Additional context**
![Scroll-Through-Image-to-Change-Text-Parallax-Effect](https://user-images.githubusercontent.com/64035221/138103171-d37a7d91-4806-4b49-9e39-db801041e364.gif)

**Comment by siddhi-244** [comment]
Assigning 🎊🎊
