### ISSUE TITLE
Adding Hover Effect to Cards

### ISSUE THREAD

**Issue by agamjotsingh18** [siddhi-244/Embellish#204]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to add shadow on hover on the cards to look more attractive.

**Describe alternatives you've considered**
No

**Comment by ShivamAgarwal-code** [comment]
Can I take up this issue?

**Comment by siddhi-244** [comment]
> Can I take up this issue?

Yes you can.
