### ISSUE TITLE
I want to add proper spacing between ul li items in the navigation bar.

### ISSUE THREAD

**Issue by zetabug** [siddhi-244/Embellish#217]
**Describe the bug**
The " Home About Team Component Contact "  items in the NAVIGATION BAR have so poor spacing between them.
![Screenshot from 2021-10-31 19-31-25](https://user-images.githubusercontent.com/72355377/139587538-ef81c5ca-baf8-4b5d-9f98-2bab1351415c.png)

**Expected behavior**
I will add proper spaces between the ul items ,I have added the screenshots that will help you understand.
![Screenshot from 2021-10-31 19-33-24](https://user-images.githubusercontent.com/72355377/139587545-83fb7d36-5fd0-46c7-800f-e4f394ddba3f.png)

Your current navigation bar is looking bad because there is no space between the " Home About Team Component Contact "  items and it all looks cluttered . Adding proper spaces will make your navbar look good.

I want you to assign me this issue. @siddhi-244

**Comment by siddhi-244** [comment]
Go for it !! Are you contributing under Hacktoberfest?

**Comment by zetabug** [comment]
> Go for it !! Are you contributing under Hacktoberfest?

I was😄, but I will do it anyway
