### ISSUE TITLE
Improve the responsiveness of the website 

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#227]
**Is your feature request related to a problem? Please describe.**
The website is not responsive 

**Describe the solution you'd like**
Make the website responsive

**Comment by aswinikalyan30** [comment]
Hey, i would like to take this up as part of opencode
I would like to fix the "aside" element as it is blocking the text behind it, and improve the responsiveness with mq

**Comment by siddhi-244** [comment]
> Hey, i would like to take this up as part of opencode I would like to fix the "aside" element as it is blocking the text behind it, and improve the responsiveness with mq

Go for it !🎊🎊
