### ISSUE TITLE
Align the navbar properly on mobile view !

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#228]

**Comment by Yuji-Itadorii** [comment]
Hey @siddhi-244, please assign this issue to me under the Open-Code event.

**Comment by siddhi-244** [comment]
> Hey @siddhi-244, please assign this issue to me under the Open-Code event.

Sure ! Go for it !🎊🎊

**Comment by siddhi-244** [comment]
![Screenshot_20220407-110830_Chrome](https://user-images.githubusercontent.com/69195262/162127936-c07e9281-aeb9-4b1a-a167-c255129c7804.jpg)
Make it something like this !

**Comment by Yuji-Itadorii** [comment]
hey @siddhi-244, I have sent the pull request please review it and let me know if there any issue you found.
