### ISSUE TITLE
Height of "more component link"

### ISSUE THREAD

**Issue by Yuji-Itadorii** [siddhi-244/Embellish#230]
I think the More component button is very close to the bottom cards as you can see in the screenshot 
<img width="953" alt="image" src="https://user-images.githubusercontent.com/93515450/162123639-3d6b6f80-add7-4bce-8f00-e119d76e3646.png">

I would like to increase the height of it so that it looks much better than the previous one (like the below screenshot)
<img width="953" alt="image" src="https://user-images.githubusercontent.com/93515450/162123858-b1550240-fc04-49c5-86d4-e6c345351fa4.png">

If you like my suggestion then please assign this enhancement under the Open code event.

**Comment by siddhi-244** [comment]
Hey! Go for it ! Just add that more components thing below the cards and increase its height!

**Comment by Yuji-Itadorii** [comment]
Hey @siddhi-244, It seems like issue #228 and #230 has already been solved.
So I found a new issue in your header buttons (as you can see in the image)
<img width="292" alt="image" src="https://user-images.githubusercontent.com/93515450/162139154-39d8bb2e-fb05-486a-8da6-e1e906a3620c.png">

So I would like to give a margin between these two buttons and the result will be like this:-
<img width="295" alt="image" src="https://user-images.githubusercontent.com/93515450/162139371-0c46a6de-b751-4cb5-b9df-4d33bbf7a230.png">

**If you like my suggestion please accept the review and accept my pull request!!**

**Comment by siddhi-244** [comment]
> Hey @siddhi-244, It seems like issue #228 and #230 has already been solved. So I found a new issue in your header buttons (as you can see in the image) <img alt="image" width="292" src="https://user-images.githubusercontent.com/93515450/162139154-39d8bb2e-fb05-486a-8da6-e1e906a3620c.png">
> 
> So I would like to give a margin between these two buttons and the result will be like this:- <img alt="image" width="295" src="https://user-images.githubusercontent.com/93515450/162139371-0c46a6de-b751-4cb5-b9df-4d33bbf7a230.png">
> 
> **If you like my suggestion please accept the review and accept my pull request!!**

Can uh take it side ways ?

**Comment by siddhi-244** [comment]
> Hey @siddhi-244, It seems like issue #228 and #230 has already been solved. So I found a new issue in your header buttons (as you can see in the image) <img alt="image" width="292" src="https://user-images.githubusercontent.com/93515450/162139154-39d8bb2e-fb05-486a-8da6-e1e906a3620c.png">
> 
> So I would like to give a margin between these two buttons and the result will be like this:- <img alt="image" width="295" src="https://user-images.githubusercontent.com/93515450/162139371-0c46a6de-b751-4cb5-b9df-4d33bbf7a230.png">
> 
> **If you like my suggestion please accept the review and accept my pull request!!**

And for #228 the navbar items need to be aligned.  I have shared the screenshots
