### ISSUE TITLE
Improve the responsiveness of the website

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#233]
![Screenshot_20220407-171646_Chrome](https://user-images.githubusercontent.com/69195262/162191750-c6f6fb6f-b0de-46d1-afe6-2e69065281d4.jpg)
![Screenshot_20220407-171652_Chrome](https://user-images.githubusercontent.com/69195262/162191756-f1f5b2e7-2d7f-4c3d-ae66-8f991ace605d.jpg)

**Comment by siddhi-244** [comment]
> ![Screenshot_20220407-171646_Chrome](https://user-images.githubusercontent.com/69195262/162191750-c6f6fb6f-b0de-46d1-afe6-2e69065281d4.jpg) ![Screenshot_20220407-171652_Chrome](https://user-images.githubusercontent.com/69195262/162191756-f1f5b2e7-2d7f-4c3d-ae66-8f991ace605d.jpg)

Improve this !

**Comment by Aniket-508** [comment]
@siddhi-244 I want to work on this issue.

**Comment by siddhi-244** [comment]
Sure !
