### ISSUE TITLE
The more components button should come below the components in mobile view !

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#238]
![Screenshot_20220420-222628_Chrome](https://user-images.githubusercontent.com/69195262/164283728-f5096651-b0fb-4850-a675-888e8f261c24.jpg)

**Comment by Saurav-Singh-Rauthan** [comment]
![Screenshot 2022-04-22 204757](https://user-images.githubusercontent.com/54982868/164744267-82f2ddfe-bc24-4f29-a924-3364831a74c5.jpg)
is this the required change?

**Comment by siddhi-244** [comment]
Yes

**Comment by Saurav-Singh-Rauthan** [comment]
can i work on it?

**Comment by siddhi-244** [comment]
Sure! Are you a opencode participant?

**Comment by Saurav-Singh-Rauthan** [comment]
Nope, is it a prerequisite?

**Comment by siddhi-244** [comment]
> Nope, is it a prerequisite?

No it's okayy. You can contribute

**Comment by Saurav-Singh-Rauthan** [comment]
I've opened a PR, can you review it
