### ISSUE TITLE
Correct all the typos and add some content wherever necessary on the website 

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#239]

**Comment by YC-Kwan** [comment]
Hi there, may I know what content should add to the website?

**Comment by siddhi-244** [comment]
There are some typos + the about page also needs help !

**Comment by siddhi-244** [comment]
> There are some typos + the contact us page also needs help !

**Comment by YC-Kwan** [comment]
> > There are some typos + the contact us page also needs help !

What the issue on the contact us page?

**Comment by siddhi-244** [comment]
> > > There are some typos + the contact us page also needs help !
> 
> What the issue on the contact us page?

Just check it out ! It needs content
