### ISSUE TITLE
Bottom margin for more components button on desktop view

### ISSUE THREAD

**Issue by Saurav-Singh-Rauthan** [siddhi-244/Embellish#244]
**Describe the bug**
More components button doesn't have proper margin on desktop view

**To Reproduce**
1. Go to [embellish website](https://embellish.netlify.app/)
2. Scroll down to more components section on desktop view

**Expected behavior**
There should be margin-bottom (preferably 3rem) for the more components button 

**Screenshots**
![error ss](https://user-images.githubusercontent.com/54982868/164914080-78bb3eab-7c6a-40f1-af9e-c452f9f4443d.jpg)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Chrome 100.0.4896.127

**Comment by Saurav-Singh-Rauthan** [comment]
Can I work on this issue?

**Comment by YC-Kwan** [comment]
Hi there, can assign this issue to me?

**Comment by siddhi-244** [comment]
Sure ! Try to bring that button below the components!

**Comment by siddhi-244** [comment]
Are you a openCode contributor ?

**Comment by Saurav-Singh-Rauthan** [comment]
> Are you a openCode contributor ?

Nope

**Comment by siddhi-244** [comment]
> > Are you a openCode contributor ?
> 
> Nope

Cool ! You can go on

**Comment by Saurav-Singh-Rauthan** [comment]
> Sure ! Try to bring that button below the components!

the button should come below the components card in  the desktop view too?

**Comment by siddhi-244** [comment]
> > Sure ! Try to bring that button below the components!
> 
> the button should come below the components card in the desktop view too?

Yes

**Comment by Saurav-Singh-Rauthan** [comment]
I've created a PR #247 , can you please review it
