### ISSUE TITLE
Change the content here ! Add discord server link of Embellish tooo ! 

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#245]
![Screenshot_20220426-080750_Chrome](https://user-images.githubusercontent.com/69195262/165208678-2b5eab23-b2c7-4822-b208-52314a2b8e5c.jpg)

**Comment by afreenabegum** [comment]
@siddhi-244 ,Please do assign it to me!

**Comment by siddhi-244** [comment]
Assigned🥳🥳

**Comment by afreenabegum** [comment]
@siddhi-244  mam like what content do we need to change specifically?

**Comment by siddhi-244** [comment]
> @siddhi-244 mam like what content do we need to change specifically?

Instead of chat with us and call us, you can add join our discord , then give our github link. Instead of support center you can add support us and give link to sponsorship page.

**Comment by siddhi-244** [comment]
Yes

**Comment by siddhi-244** [comment]
Change ask the community part too. And you literally removed call us part . Why ? Don't remove that part

**Comment by afreenabegum** [comment]
> Change ask the community part too. And you literally removed call us part . Why ? Don't remove that part

@siddhi-244 , before u said to remove call us and chat with us part, I'll work on it now as you said .

**Comment by siddhi-244** [comment]
I said remove that part and add other parts. I didn't ask you to completely remove that part !
