### ISSUE TITLE
Fix footer links. We dont need privacy and terms ! You can add about us and components instead of that and link to about page and components page respectively!

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#246]
![Screenshot_20220426-080957_Chrome](https://user-images.githubusercontent.com/69195262/165209063-d520bb09-0b40-4e24-9846-8ce1cade639c.jpg)

Change our team to contributors!

**Comment by siddhi-244** [comment]
> I would like to work on this issue!

Are you hsoc participant,?

**Comment by tanya-gupta25** [comment]
> > I would like to work on this issue!
> 
> Are you hsoc participant,?

Yeah I am an HSOC participant

**Comment by siddhi-244** [comment]
Cool ! You can start working on it🎊🎊
