### ISSUE TITLE
Placeholder and label name overlap on the contact form.

### ISSUE THREAD

**Issue by Abrosss** [siddhi-244/Embellish#250]
**Describe the bug**
Hello! There's some overlapping on the contact form on the **contact page.** 

![Screenshot_2](https://user-images.githubusercontent.com/84074575/165470960-9ab79a91-bf67-4f08-aa44-b854a387eb82.png)

I tried to fix it and make it look like this:

![fixed](https://user-images.githubusercontent.com/84074575/165471635-cfd655b7-c943-480b-89f8-cc9116c98528.gif)

If this solution works, and the problem is relevant, I would like to fix it.

**Comment by siddhi-244** [comment]
> **Describe the bug** Hello! There's some overlapping on the contact form on the **contact page.**
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/84074575/165470960-9ab79a91-bf67-4f08-aa44-b854a387eb82.png)
> 
> I tried to fix it and make it look like this:
> 
> ![fixed](https://user-images.githubusercontent.com/84074575/165471635-cfd655b7-c943-480b-89f8-cc9116c98528.gif)
> 
> If this solution works, and the problem is relevant, I would like to fix it.

Assigning this to you!
