### ISSUE TITLE
Update the Readme

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#253]
**Is your feature request related to a problem? Please describe.**
Whenever you add a new component,  you need to add its details in the json file. So add this step in readme.

**Describe the solution you'd like**
Add this step in the readme with an example on how to write json.

**Comment by afreenabegum** [comment]
@siddhi-244 please do assign it to me !!

**Comment by siddhi-244** [comment]
Go ahead

**Comment by afreenabegum** [comment]
@siddhi-244 I have a doubt mam , please help me with this!
Basically what I need to do?

**Comment by siddhi-244** [comment]
> @siddhi-244 I have a doubt mam , please help me with this! Basically what I need to do?
> 
> I need to add above two steps in the readme file? Is it mam?

In the readme, in instructions while contributing section. Add one more point stating 
- Add details about your component in the json file as follows 
```
``
This is what you have to do. Check the json file, see the format and give example in a code block.
