### ISSUE TITLE
Adding Glassmorphism-loader

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#258]
**Is your feature request related to a problem? Please describe.**
When we open the website we a good-looking loader.

**Describe the solution you'd like**
I am going to add a loading effect using glassmorphism.

**Additional context**
 

https://user-images.githubusercontent.com/98695632/179336845-f7d6ae75-e36e-4a68-bcc2-9d35aa3fbd7c.mp4

**Comment by siddhi-244** [comment]
Hey, this is available on YouTube too. Can you work more on it and make something different? Then share the video again ! I will assign this issue to you once you make something different

**Comment by yashkondewar** [comment]
https://user-images.githubusercontent.com/98695632/179339156-e0ed8cda-f27a-4840-ac82-695659c0210d.mp4

Can I add this??

**Comment by siddhi-244** [comment]
Cool go on

**Comment by siddhi-244** [comment]
Next time please link the issue with the pr!

**Comment by yashkondewar** [comment]
> Next time please link the issue with the pr!

OK mam,
Thank You!!
