### ISSUE TITLE
CSS loading animation 

### ISSUE THREAD

**Issue by srinjoy-26** [siddhi-244/Embellish#259]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Add a new animation in css.

**Describe alternatives you've considered**
nothing.

**Additional context**

https://user-images.githubusercontent.com/91176055/179367809-e3d6cf0e-f4e3-4306-a085-2ca3555c1915.mp4

**Comment by siddhi-244** [comment]
Please fill the issue template properly.  And also attach a gif or screenshot

**Comment by srinjoy-26** [comment]
> Please fill the issue template properly. And also attach a gif or screenshot

Okke 🙂

**Comment by siddhi-244** [comment]
Assigning it to you !
