### ISSUE TITLE
Add Animated Background

### ISSUE THREAD

**Issue by shreyamedehal** [siddhi-244/Embellish#26]
**Is your feature request related to a problem? Please describe.**
Animated Background 

**Describe the solution you'd like**
Animated Background using pure css and html

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Animated Background
> 
> **Describe the solution you'd like** Animated Background using pure css and html

Assigning this to you !🎊🎊🎊🎊🎊make sure you follow previous merged prs.
