### ISSUE TITLE
Glowing  icons  with hover effect.

### ISSUE THREAD

**Issue by srinjoy-26** [siddhi-244/Embellish#260]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Add a new animation in css.

**Describe alternatives you've considered**
nothing.

**Additional context**
<img width="960" alt="157488714-30397058-2d13-4327-ae53-672cba920136" src="https://user-images.githubusercontent.com/91176055/179367034-f30fe521-5abd-4802-93c8-25159747109b.png">

**Comment by siddhi-244** [comment]
Please fill issue template properly and add a screenshot or gif of the component you have planned

**Comment by srinjoy-26** [comment]
> Please fill issue template properly and add a screenshot or gif of the component you have planned

Ok 🙂

**Comment by siddhi-244** [comment]
Assigning it to you
