### ISSUE TITLE
Adding Profile card to card components.

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#261]
**Is your feature request related to a problem? Please describe.**
We need to share our details many times.

**Describe the solution you'd like**
I made a profile card so that one can share their details with anyone.

**Describe alternatives you've considered**
I made a profile card using HTML and CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/179393328-505722ee-f35d-4e58-8ab7-c33c059765de.mp4

**Comment by siddhi-244** [comment]
Assigning it to you🥳🥳
