### ISSUE TITLE
Adding Simple Navigatin Bar

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#268]
**Is your feature request related to a problem? Please describe.**
Every website needs a navigation bar.

**Describe the solution you'd like**
I have a simple nav bar that anyone can use on their website.

**Describe alternatives you've considered**
I have created a nav bat using HTML and CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/180272869-43b97d67-4515-41d8-be2e-3041f1e3ab61.mp4

**Comment by siddhi-244** [comment]
Assigning it to you !
