### ISSUE TITLE
Improve the general readme

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#269]
**Is your feature request related to a problem? Please describe.**
Add the components to general readme and improve it wherever it is not linked.

**Comment by afreenabegum** [comment]
Assign it to me !! @siddhi-244

**Comment by Rakesh9100** [comment]
> **Is your feature request related to a problem? Please describe.** Add the components to general readme and improve it wherever it is not linked.

Kindly assign this issue to me.

**Comment by siddhi-244** [comment]
> > **Is your feature request related to a problem? Please describe.** Add the components to general readme and improve it wherever it is not linked.
> 
> Kindly assign this issue to me.

Assigning it to you !
