### ISSUE TITLE
Glassmorphism Card

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [siddhi-244/Embellish#271]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a Glassmorphism Card 

**Describe alternatives you've considered**
nothing

**Additional context**
<img width="658" alt="Screenshot 2022-07-22 185848" src="https://user-images.githubusercontent.com/73753957/180449585-ba04cf25-91eb-43dc-a5a6-bc90df338151.png">

**Comment by siddhi-244** [comment]
Assigning it to you🥳
