### ISSUE TITLE
Day Night Hover effect

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [siddhi-244/Embellish#275]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add day Night Hover effect

**Describe alternatives you've considered**
Nothing

**Additional context**

https://user-images.githubusercontent.com/73753957/180612543-4a0c0981-f917-46a2-a371-4f4d19c11a0c.mp4

**Comment by gurjeetsinghvirdee** [comment]
@siddhi-244

**Comment by siddhi-244** [comment]
Assigned🥳🥳
