### ISSUE TITLE
Add a scrollbar 

### ISSUE THREAD

**Issue by srinjoy-26** [siddhi-244/Embellish#279]
**Is your feature request related to a problem? Please describe.**
 A scrollbar made using HTML-CSS.

**Describe the solution you'd like**
add the project.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot 2022-07-26 214149](https://user-images.githubusercontent.com/91176055/181057160-d7c8af19-bae0-42e7-8338-1a8409fec449.png)

**Comment by srinjoy-26** [comment]
@siddhi-244 please assign and also tell me under which directory will I add this project

**Comment by siddhi-244** [comment]
> @siddhi-244 please assign and also tell me under which directory will I add this project

It would be great if you can make designed scroll effects

**Comment by srinjoy-26** [comment]
> > @siddhi-244 please assign and also tell me under which directory will I add this project
> 
> It would be great if you can make designed scroll effects

Yeah I will make that in another issue, this issue is regarding the "scrollbar" which I have created and designed using html-css

**Comment by khushimarothi** [comment]
Please assign this issue to me.

**Comment by srinjoy-26** [comment]
> Please assign this issue to me.

Are you kidding me 🤣

**Comment by siddhi-244** [comment]
> > > @siddhi-244 please assign and also tell me under which directory will I add this project
> > 
> > 
> > It would be great if you can make designed scroll effects
> 
> Yeah I will make that in another issue, this issue is regarding the "scrollbar" which I have created and designed using html-css

Will close this one as it seems really simple. You can open another one.
