### ISSUE TITLE
Button Ripple Effect

### ISSUE THREAD

**Issue by SumitKanth** [siddhi-244/Embellish#280]
Will create 2 buttons with ripple effect on Click Using css & Javascript.
Will contribute under HSOC22

**Comment by siddhi-244** [comment]
> Will create 2 buttons with ripple effect on Click Using css & Javascript. Will contribute under HSOC22

Follow the issue template and add the gif of the component

**Comment by SumitKanth** [comment]
Mean ?

**Comment by siddhi-244** [comment]
> Mean ?

Video of the  button ? I need to see if it already exists

**Comment by SumitKanth** [comment]
What I have to do ?

**Comment by SumitKanth** [comment]
@siddhi-244 I have not made it, do I made it and show to you ?

**Comment by siddhi-244** [comment]
Umm yaa. I need to see the design.

**Comment by SumitKanth** [comment]
@siddhi-244 I have created design now how can I show it to you ?

**Comment by siddhi-244** [comment]
Share a ss

**Comment by SumitKanth** [comment]
![Screenshot (301)](https://user-images.githubusercontent.com/90907720/183139140-64953f4f-585c-4020-affe-f05c0b032589.png)
Can't see ripple effect in ss

**Comment by siddhi-244** [comment]
We already have many buttons. You can try another design.

**Comment by SumitKanth** [comment]
but we don't have ripple effect buttons
