### ISSUE TITLE
Testimonial Section

### ISSUE THREAD

**Issue by khushimarothi** [siddhi-244/Embellish#282]
Adding a testimonial section enhances the consumers trust on the services offered. so i would like to add the code for the testimonial section.

**Comment by siddhi-244** [comment]
> Adding a testimonial section enhances the consumers trust on the services offered. so i would like to add the code for the testimonial section.

Is it a component or you want to add it on website ? Follow the issue template

**Comment by khushimarothi** [comment]
Basically it is a feature that can be added on the website.
Please refer the ss attached.
![testimonial](https://user-images.githubusercontent.com/85816852/181162546-4dfc504a-e483-49d7-ade3-4e676a079463.png)

**Comment by siddhi-244** [comment]
> Basically it is a feature that can be added on the website. Please refer the ss attached. ![testimonial](https://user-images.githubusercontent.com/85816852/181162546-4dfc504a-e483-49d7-ade3-4e676a079463.png)

No we don't need testimonials on website. If you wanna add it as a component you can

**Comment by khushimarothi** [comment]
Bootstrap can be used in the code or not?

**Comment by siddhi-244** [comment]
> Bootstrap can be used in the code or not?

You can use it.

**Comment by siddhi-244** [comment]
Are you going to add it as a component? So that I can assign the issue to you !

**Comment by khushimarothi** [comment]
Yes, you can assign it to me.
