### ISSUE TITLE
Want to add some hover effect on header navbar and footer navbar

### ISSUE THREAD

**Issue by muditchoudhary** [siddhi-244/Embellish#283]
**Is your feature request related to a problem? Please describe.**
There is no hover effect on the navigation links which does not look good and little confusing if they are clickable or not.

**Describe the solution you'd like**
I would like to add some hover effect on the links may be an underline or a change in the text color.

**Describe alternatives you've considered**
Don't have an alternative consideration for this issue.

**Additional context**
NO

**Comment by siddhi-244** [comment]
Assigning it to you
