### ISSUE TITLE
Parallax scrolling website

### ISSUE THREAD

**Issue by srinjoy-26** [siddhi-244/Embellish#285]
**Is your feature request related to a problem? Please describe.**
A scrolling website with parallax effect.
Made using
HTML , CSS , JS

**Describe the solution you'd like**
will add the project.

**Describe alternatives you've considered**
none

**Additional context**

https://user-images.githubusercontent.com/91176055/181542919-15839304-b9f8-4e79-95da-b5eaff550295.mp4

**Comment by siddhi-244** [comment]
Assigning it to you 🥳🥳
