### ISSUE TITLE
FOOTER

### ISSUE THREAD

**Issue by Akanksha-Sen** [siddhi-244/Embellish#289]
**Is your feature request related to a problem? Please describe.**
Footer

**Describe the solution you'd like**
Want to add footer section.

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Footer
> 
> **Describe the solution you'd like** Want to add footer section.

We don't need it

**Comment by siddhi-244** [comment]
Closing this as the issue is not descriptive
