### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Akanksha-Sen** [siddhi-244/Embellish#290]
**Is your feature request related to a problem? Please describe.**
Documentation

**Describe the solution you'd like**
Improve text part of site.

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Documentation
> 
> **Describe the solution you'd like** Improve text part of site.

Please be more descriptive

**Comment by siddhi-244** [comment]
Closing this issue as it's not descriptive and no response yet

**Comment by siddhi-244** [comment]
``
