### ISSUE TITLE
Adding Hover Button

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#291]
**Is your feature request related to a problem? Please describe.**
Sometimes we need attractive buttons.

**Describe the solution you'd like**
I made a button with a hover effect

**Describe alternatives you've considered**
I used HTML,CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/182357231-994ccc4b-6913-412f-ac81-d1d5df3b3e34.mp4

**Comment by siddhi-244** [comment]
The button is too simple
