### ISSUE TITLE
Adding Toggle Button

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#292]
**Is your feature request related to a problem? Please describe.**
We need to toggle between two things.

**Describe the solution you'd like**
I have created a toggle button.

**Describe alternatives you've considered**
I used HTML,CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/182358189-81ad5336-812a-4f6b-8b9e-f3c7e88ec611.mp4

**Comment by siddhi-244** [comment]
Assigning it to you🥳🥳
