### ISSUE TITLE
Adding Login Form

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#293]
**Is your feature request related to a problem? Please describe.**
Sometimes we need a login page.

**Describe the solution you'd like**
I have created a login page that takes an input of username and password.

**Describe alternatives you've considered**
I created this using HTML and CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/182360098-cfcf9a56-e133-4f22-a5f0-acdc21d36405.mp4

**Comment by siddhi-244** [comment]
Assigning it to you🥳🥳
