### ISSUE TITLE
Adding Radio Button

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#294]
**Is your feature request related to a problem? Please describe.**
We need a radio button to select options.

**Describe the solution you'd like**
I have created a radio button.

**Describe alternatives you've considered**
I have created it using HTML and CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/182361497-7511395b-2a41-404c-8182-7d1506c596da.mp4

**Comment by siddhi-244** [comment]
Again too simple
