### ISSUE TITLE
button with ripple effect

### ISSUE THREAD

**Issue by srinjoy-26** [siddhi-244/Embellish#297]
**Is your feature request related to a problem? Please describe.**
two buttons with ripple effect made using html - css , js.

**Describe the solution you'd like**
Add this project

**Describe alternatives you've considered**
none

**Additional context**
![Screenshot 2022-08-03 200541](https://user-images.githubusercontent.com/91176055/182636193-db8a0cea-01c6-4422-8c8c-ca0990b14bf6.png)

**Comment by siddhi-244** [comment]
We already many buttons. If you can bring in more designed button it would be great
