### ISSUE TITLE
Form Validate

### ISSUE THREAD

**Issue by khushimarothi** [siddhi-244/Embellish#301]
**Is your feature request related to a problem? Please describe.**
Add a form with validation using  JavaScript as a component.

**Describe the solution you'd like**
The form will validate the entered data from the user . Tech used: Html, Css, JavaScript.
Basically it will check  if the user entered a value for a field is valid or not.
ex: phone no. - if the user enters digit less than 10 in that field it will generate the error. else not.

**Comment by siddhi-244** [comment]
We don't need it
