### ISSUE TITLE
Mobile Navigation

### ISSUE THREAD

**Issue by Rakesh9100** [siddhi-244/Embellish#304]
**Is your feature request related to a problem? Please describe.**
Project related to Navigation that is Mobile Navigation.

**Describe the solution you'd like**
Add the Project.

**Comment by Rakesh9100** [comment]
Kindly see to this @siddhi-244

**Comment by siddhi-244** [comment]
Go on🙌

**Comment by siddhi-244** [comment]
One min
I have a question

**Comment by siddhi-244** [comment]
We need components and not the whole page

**Comment by Rakesh9100** [comment]
> We need components and not the whole page

Components like can you brief ? @siddhi-244
