### ISSUE TITLE
Adding Flipping Cards

### ISSUE THREAD

**Issue by yashkondewar** [siddhi-244/Embellish#305]
**Is your feature request related to a problem? Please describe.**
We need cards sometimes.

**Describe the solution you'd like**
I have created Flipping Cards.

**Describe alternatives you've considered**
Used HTML and CSS.

**Additional context**

https://user-images.githubusercontent.com/98695632/184938660-98aa9d96-51ba-4cb9-8b5b-784ba15e38b8.mp4

**Comment by siddhi-244** [comment]
Go ahead !
