### ISSUE TITLE
Create hover effects for all the buttons

### ISSUE THREAD

**Issue by pranavsuriya-sr** [siddhi-244/Embellish#307]
**Is your feature request related to a problem? Please describe.**
Add hovering effects to all the buttons in the website. When the cursor is placed on the respective buttons, the buttons can exhibit some change like, the background color changes or the font color changes.

**Comment by siddhi-244** [comment]
can you add a gif?

**Comment by pranavsuriya-sr** [comment]
gif......is it like the change should repeat?? something like this  

https://user-images.githubusercontent.com/91081814/186688411-7434630b-5022-4744-8ea3-2601c60d239e.mp4

**Comment by siddhi-244** [comment]
We already have such buttons. We need designed components
