### ISSUE TITLE
ui: Scroll bar is not visible

### ISSUE THREAD

**Issue by niladrix719** [siddhi-244/Embellish#317]
**Describe the bug**
The page does have a scroll bar but its not visible

**To Reproduce**
1. Go to 'https://embellish.netlify.app/'
2. See error 'scroll bar not visible'

**Expected behavior**
we can either remove the scroll bar as it is taking some space or we can make it visible with suitable color

**Screenshots**
![Screenshot from 2023-02-01 21-01-56](https://user-images.githubusercontent.com/91966855/216087427-3b6ab5b6-c5b1-446b-8ec0-eb694c7c9d95.png)

**Desktop (please complete the following information):**
 - OS: [ubuntu 22]
 - Browser [chrome]
 - Version [22]

**Comment by siddhi-244** [comment]
Assigning it to you
