### ISSUE TITLE
The component preview button shows page not found error

### ISSUE THREAD

**Issue by Subhrajit-Dutta** [siddhi-244/Embellish#321]
The component preview button shows **page not found** error

1. Go to 'https://embellish.netlify.app/'
2. Scroll down to our components section
3. Click on 'preview'

**Expected behavior**
The respective website should open upon clicking the preview button.

![image](https://user-images.githubusercontent.com/98512995/216107359-3ecd5291-8743-40ea-a273-cbc00259d5a5.png)

![image](https://user-images.githubusercontent.com/98512995/216107430-08dd11ba-3468-49ff-beeb-be8a968b2997.png)

**Comment by siddhi-244** [comment]
> The component preview button shows **page not found** error
> 
> Steps to reproduce the behavior:
> 
> 1. Go to 'https://embellish.netlify.app/'
> 2. Scroll down to our components section
> 3. Click on 'preview'
> 4. See error
> 
> **Expected behavior** The respective website should open upon clicking the preview button.
> 
> ![image](https://user-images.githubusercontent.com/98512995/216107359-3ecd5291-8743-40ea-a273-cbc00259d5a5.png)
> 
> ![image](https://user-images.githubusercontent.com/98512995/216107430-08dd11ba-3468-49ff-beeb-be8a968b2997.png)

Go for it !

**Comment by niladrix719** [comment]
> The component preview button shows **page not found** error
> 
> Steps to reproduce the behavior:
> 
> 1. Go to 'https://embellish.netlify.app/'
> 2. Scroll down to our components section
> 3. Click on 'preview'
> 4. See error
> 
> **Expected behavior** The respective website should open upon clicking the preview button.
> 
> ![image](https://user-images.githubusercontent.com/98512995/216107359-3ecd5291-8743-40ea-a273-cbc00259d5a5.png)
> 
> ![image](https://user-images.githubusercontent.com/98512995/216107430-08dd11ba-3468-49ff-beeb-be8a968b2997.png)

are you still working on this? i think I might fix this issue

**Comment by niladrix719** [comment]
@Subhrajit-Dutta are you still working on this? i think i might fix this, should I work on this?

**Comment by Subhrajit-Dutta** [comment]
@niladrix719 Yeah I'm working on it. If I need help I'll ask you.

**Comment by niladrix719** [comment]
@Subhrajit-Dutta sure

**Comment by Subhrajit-Dutta** [comment]
I think the problem is with netlify because locally it's working fine but the problem occurs on deployed netlify website. What do you think? @niladrix719

**Comment by siddhi-244** [comment]
You can do one thing  ! Put the html+css+js folder inside the Embellish website folder and change all the path in componentData.json. it might work

**Comment by SurajPratap10** [comment]
> I think the problem is with netlify because locally it's working fine but the problem occurs on deployed netlify website. What do you think? @niladrix719

Ya, the same thing happened to me too, when I added the AutoTyping animation on the Website. In my system when I ran the code the component section was coming but on the preview deployed site via Netlify it somehow vanished.

**Comment by Subhrajit-Dutta** [comment]
> You can do one thing ! Put the html+css+js folder inside the Embellish website folder and change all the path in componentData.json. it might work

Okay ill try this

**Comment by Subhrajit-Dutta** [comment]
> You can do one thing ! Put the html+css+js folder inside the Embellish website folder and change all the path in componentData.json. it might work

Hey! I tried doing this but cannot push the change to a separate branch. The file structure gets modified for the main branch too. Also, how shall I know if the problem is fixed because locally it would show the pages, only after deploying we get to know if there's any error.

**Comment by siddhi-244** [comment]
> > You can do one thing ! Put the html+css+js folder inside the Embellish website folder and change all the path in componentData.json. it might work
> 
> Hey! I tried doing this but cannot push the change to a separate branch. The file structure gets modified for the main branch too. Also, how shall I know if the problem is fixed because locally it would show the pages, only after deploying we get to know if there's any error.

You can take help from @niladrix719

**Comment by niladrix719** [comment]
@Subhrajit-Dutta hey, can you please describe the problem of pushing the changes to a separate branch? And about the Deploy Part, I guess you can make changes and Post a Draft PR so that you can have a deploy preview, and if the error still remains you can always commit afterwards

**Comment by niladrix719** [comment]
> @Subhrajit-Dutta hey, can you please describe the problem of pushing the changes to a separate branch? And about the Deploy Part, I guess you can make changes and Post a Draft PR so that you can have a deploy preview, and if the error still remains you can always commit afterward. You can ping me in discord if you want Niladri#8723

**Comment by Subhrajit-Dutta** [comment]
@siddhi-244 I and @niladrix719 tried putting the HTML+CSS+JS folder in the embellish-website folder but the issue still persists. I think it's some problem with netlify.

**Comment by siddhi-244** [comment]
> @siddhi-244 I and @niladrix719 tried putting the HTML+CSS+JS folder in the embellish-website folder but the issue still persists. I think it's some problem with netlify.

We can try changing the preview path ! If you have any another solution @niladrix719 @Subhrajit-Dutta then go for it

**Comment by niladrix719** [comment]
> > @siddhi-244 I and @niladrix719 tried putting the HTML+CSS+JS folder in the embellish-website folder but the issue still persists. I think it's some problem with netlify.
> 
> We can try changing the preview path ! If you have any another solution @niladrix719 @Subhrajit-Dutta then go for it

we have actually tried changing the preview path but still, the issue remains, locally it runs fine..error is only there for the netlify deployment, there might be some issue with netlify

**Comment by siddhi-244** [comment]
> > > @siddhi-244 I and @niladrix719 tried putting the HTML+CSS+JS folder in the embellish-website folder but the issue still persists. I think it's some problem with netlify.
> > 
> > 
> > We can try changing the preview path ! If you have any another solution @niladrix719 @Subhrajit-Dutta then go for it
> 
> we have actually tried changing the preview path but still, the issue remains, locally it runs fine..error is only there for the netlify deployment, there might be some issue with netlify

Have a look at this
![Screenshot_20230206-190758_Chrome](https://user-images.githubusercontent.com/69195262/216985757-2fe6a205-1b01-484d-b6c3-1301e4b92513.jpg)

**Comment by siddhi-244** [comment]
You guys can refer this 
https://github.com/siddhi-244/propack/tree/main/projects
@niladrix719 @Subhrajit-Dutta

**Comment by niladrix719** [comment]
@siddhi-244 @Subhrajit-Dutta 
![Screenshot from 2023-02-06 19-23-50](https://user-images.githubusercontent.com/91966855/216989545-b67db3da-7747-4197-a838-8fd4a08e0898.png)
not sure but is keeping publish directory not set causing the error..

**Comment by siddhi-244** [comment]
It's set already 
![Screenshot_20230206-193318_Chrome](https://user-images.githubusercontent.com/69195262/216991793-c1208f13-f2ed-42c0-9bd6-0694333987cb.jpg)

**Comment by siddhi-244** [comment]
Folks I got what's the issue is !
@niladrix719 @Subhrajit-Dutta 
The preview path in componentData.json should be html+css+js/{folder name}/{component} you need to change all the paths ! Did you get it?

**Comment by niladrix719** [comment]
> Folks I got what's the issue is ! @niladrix719 @Subhrajit-Dutta The preview path in componentData.json should be html+css+js/{folder name}/{component} you need to change all the paths ! Did you get it?

ok let me try

**Comment by niladrix719** [comment]
> Folks I got what's the issue is ! @niladrix719 @Subhrajit-Dutta The preview path in componentData.json should be html+css+js/{folder name}/{component} you need to change all the paths ! Did you get it?

just moved the folder inside and it does work now
