### ISSUE TITLE
New Gradient Background with flow effect

### ISSUE THREAD

**Issue by SurajPratap10** [siddhi-244/Embellish#327]
**Is your feature request related to a problem? Please describe.**
I want to add a new component under the Background folder named Gradient_Background. That generated a real-time flow of waves in the footer with the gradient switch in the Bg giving the website a more dynamic look.

**Describe the solution you'd like**
I will add this new component via a PR

**Describe alternatives you've considered**

**Additional context**
![Gradient_Background — Mozilla Firefox 2023-02-02 09-30-59](https://user-images.githubusercontent.com/92919173/216229042-db762c85-a802-4368-8ef6-640f60ab7f6f.gif)

**Comment by siddhi-244** [comment]
Go for it
