### ISSUE TITLE
Feature: Floating Cube Animation

### ISSUE THREAD

**Issue by niladrix719** [siddhi-244/Embellish#329]
**Is your feature request related to a problem? Please describe.**
I would like to add an animation that provides an 3D effect to the web page

**Describe the solution you'd like**
Adding an Animation under the animation section

**Describe alternatives you've considered**

[screen-recording.webm](https://user-images.githubusercontent.com/91966855/216248767-09e980f0-e852-49d2-96a0-ca934660a031.webm)

**Additional context**

**Comment by siddhi-244** [comment]
Go for it !
