### ISSUE TITLE
Contact Component

### ISSUE THREAD

**Issue by IAmTamal** [siddhi-244/Embellish#33]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a Problem. 

**Describe the solution you'd like**
I wanted to add a professional "Contact Info" component which can be used anywhere in any site providing it with a clean and professional look.

**Describe alternatives you've considered**
Nil.

**Additional context**
Nil

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊🎊
