### ISSUE TITLE
Feature: Contact Form Layout

### ISSUE THREAD

**Issue by niladrix719** [siddhi-244/Embellish#330]
**Is your feature request related to a problem? Please describe.**
I would like to add a contact form to the components in the contact form section

**Describe the solution you'd like**
Adding a Contact form Component

**Describe alternatives you've considered**

![Screenshot from 2023-02-02 11-41-07](https://user-images.githubusercontent.com/91966855/216248155-194560e5-6043-4764-b186-36aef2c7b709.png)

**Additional context**

**Comment by siddhi-244** [comment]
Go for it!
