### ISSUE TITLE
Feature: Dynamic_Progress_Bar

### ISSUE THREAD

**Issue by SurajPratap10** [siddhi-244/Embellish#334]
**Is your feature request related to a problem? Please describe.**
To add a Dynamic Progress Bar Component in the repo.

**Describe the solution you'd like**
I will add a component to the Progress-bar folder.

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/92919173/216295957-4b303ebe-53b9-4ddf-89a6-a7f818c33b81.mp4

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** To add a Dynamic Progress Bar Component in the repo.
> 
> **Describe the solution you'd like** I will add a component to the Progress-bar folder.
> 
> **Describe alternatives you've considered** A clear and concise description of any alternative solutions or features you've considered.
> 
> **Additional context** Add any other context or screenshots about the feature request here.
> 
>  Embellish.Mozilla.Firefox.2023-02-02.15-37-04.mp4

Go for it !
