### ISSUE TITLE
Feature: AutoTyping-Text-Animation  

### ISSUE THREAD

**Issue by SurajPratap10** [siddhi-244/Embellish#340]
**Is your feature request related to a problem? Please describe.**
I would like to add a new component that automatically re-writes texts on it's own at a set time interval.

**Describe the solution you'd like**
The Auto-Typing feature will make the websites look more dynamic and appealing.

**Describe alternatives you've considered**

**Additional context**

https://user-images.githubusercontent.com/92919173/216388900-f25a29a2-83c2-4346-8aa3-a6d2254d2229.mp4

**Comment by siddhi-244** [comment]
We already have it
