### ISSUE TITLE
Feature: Categories need to be introduced

### ISSUE THREAD

**Issue by niladrix719** [siddhi-244/Embellish#348]
**Is your feature request related to a problem? Please describe.**

1. The user gets the components randomly. But most users mainly come to a website looking for something in particular

2.  The Get Started button on the page is sending the user to the Feature section, which should not be the ideal case as it should rather send the user to the Category section

**Describe the solution you'd like**

1. A Category section for the Components needs to be on the page so the user can select the category that the user is looking for, rather than searching randomly. After clicking on a particular category the user will be shown components of that category only.

2. The Get Started button on the page should navigate the user to the Category section rather than the features section

3. The 3 random components at the bottom of the page should be kept as it is, as we can use them as random suggestions

**The Category Section DEMO:**

![Screenshot from 2023-02-04 10-25-56](https://user-images.githubusercontent.com/91966855/216749421-674e84f4-b224-4cf2-9216-c56feca443ad.png)

[screen-recording (5).webm](https://user-images.githubusercontent.com/91966855/216749809-b293159e-f778-4f71-a259-68fcee535752.webm)

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> 1. The user gets the components randomly. But most users mainly come to a website looking for something in particular
> 2. The Get Started button on the page is sending the user to the Feature section, which should not be the ideal case as it should rather send the user to the Category section
> 
> **Describe the solution you'd like**
> 
> 1. A Category section for the Components needs to be on the page so the user can select the category that the user is looking for, rather than searching randomly. After clicking on a particular category the user will be shown components of that category only.
> 2. The Get Started button on the page should navigate the user to the Category section rather than the features section
> 3. The 3 random components at the bottom of the page should be kept as it is, as we can use them as random suggestions
> 
> **The Category Section DEMO:**
> 
> ![Screenshot from 2023-02-04 10-25-56](https://user-images.githubusercontent.com/91966855/216749421-674e84f4-b224-4cf2-9216-c56feca443ad.png)
> 
>  screen-recording.5.webm

Amazing observation and enhancement. Make sure you remove the box around our components heading. Rest it's awesome and make sure the components are linked too as in if we click on background all the cards with background category should be visible on other page !

**Comment by siddhi-244** [comment]
Awesome work. Great enhancement !
