### ISSUE TITLE
Need some Hover Animation Effect

### ISSUE THREAD

**Issue by Rupayan20** [siddhi-244/Embellish#350]
Here button is quite basic and need to modify the buttons and make it more animated and add styling to the buttons.
This is very important for attracting users.

**Comment by siddhi-244** [comment]
> Here button is quite basic and need to modify the buttons and make it more animated and add styling to the buttons. This is very important for attracting users.

Can you please use the issue template and be more descriptive.  I can't get which buttons are you talking about.
