### ISSUE TITLE
Update: Our Components

### ISSUE THREAD

**Issue by SurajPratap10** [siddhi-244/Embellish#354]
**Is your feature request related to a problem? Please describe.**
1)Removing the box shadow part as it doesn't match the styling of other sections of the website
2) Increasing the font weight of the Our Components title, such that it could look the same as the rest of the sections of the website.
3) Removing the Uppercase as this has not been followed in any sections and it looks out of context in a single place.
**Describe the solution you'd like**
1)Removing the box shadow and Uppercase
2)Increasing the font weight
**Describe alternatives you've considered**

**Additional context**

*Before*
![f2](https://user-images.githubusercontent.com/92919173/216832700-536b0b93-f3c0-4a6b-aad4-479c160fb36c.png)
*After*
![f1](https://user-images.githubusercontent.com/92919173/216832729-e1f537fb-5fab-46e3-beeb-f04694dbca3e.png)

**Comment by niladrix719** [comment]
@SurajPratap10 looks good. One addition you can do 'components you may like' section heading can have some bottom margins to follow the rest headings

**Comment by SurajPratap10** [comment]
> @SurajPratap10 looks good. One addition you can do 'components you may like' section heading can have some bottom margins to follow the rest headings. what do you say?

Ya, for sure. Thanks for reminding me of that.

**Comment by siddhi-244** [comment]
Just remove the borders and make it similar to other headings in the website

**Comment by SurajPratap10** [comment]
> Just remove the borders and make it similar to other headings in the website

you agree with the after pic right, or anything else?

**Comment by siddhi-244** [comment]
Yay
Just center the lines below it!

**Comment by SurajPratap10** [comment]
> Yay Just center the lines below it!

ok
