### ISSUE TITLE
Add rotating Text Sphere.

### ISSUE THREAD

**Issue by Asmit2952** [siddhi-244/Embellish#36]
**Is your feature request related to a problem? Please describe.**
Adding an animated text sphere using a JS library which rotates on mouse hover 

**Describe the solution you'd like**
I will add a working demo

**Comment by siddhi-244** [comment]
You have to use vanilla js

**Comment by Asmit2952** [comment]
> You have to use vanilla js

There's a simple library called TagCloud.js, we can implement using vanilla js but the code is around 2000 lines

**Comment by siddhi-244** [comment]
You can try with another components
