### ISSUE TITLE
In dark mode, category titles gets hidden upon hovering

### ISSUE THREAD

**Issue by Subhrajit-Dutta** [siddhi-244/Embellish#360]
In dark mode, category titles gets hidden upon hovering.

![Untitled video - Made with Clipchamp (1)](https://user-images.githubusercontent.com/98512995/216967639-2c2e5d4d-03e8-4c95-8a57-2c550c8b27a0.gif)

**Comment by siddhi-244** [comment]
> In dark mode, category titles gets hidden upon hovering.
> 
> ![Untitled video - Made with Clipchamp (1)](https://user-images.githubusercontent.com/98512995/216967639-2c2e5d4d-03e8-4c95-8a57-2c550c8b27a0.gif) [ ![Untitled video - Made with Clipchamp (1)](https://user-images.githubusercontent.com/98512995/216967639-2c2e5d4d-03e8-4c95-8a57-2c550c8b27a0.gif) ](https://user-images.githubusercontent.com/98512995/216967639-2c2e5d4d-03e8-4c95-8a57-2c550c8b27a0.gif) [ ](https://user-images.githubusercontent.com/98512995/216967639-2c2e5d4d-03e8-4c95-8a57-2c550c8b27a0.gif)

I didn't understand the issue!

**Comment by shyamtawli** [comment]
@siddhi-244 When you hover in dark mode the titles like "Text-Animation , Testimonial, etc" are not showing or get hidden.

**Comment by siddhi-244** [comment]
I think thats fine! It looks good

**Comment by Subhrajit-Dutta** [comment]
I think it will be better if we could see the text even in dark mode. I just tried it please have a look.
