### ISSUE TITLE
Fix the footer to the bottom !

### ISSUE THREAD

**Issue by siddhi-244** [siddhi-244/Embellish#362]
![Screenshot (430)](https://user-images.githubusercontent.com/69195262/217002672-27d2dfbc-5a2c-42ff-8ea1-08df7b416bc6.png)

Please work on the issue !

**Comment by SurajPratap10** [comment]
It's not happening on my end

**Comment by SurajPratap10** [comment]
Ok , it's happening when we click over the newly made component section

**Comment by SurajPratap10** [comment]
assign

**Comment by siddhi-244** [comment]
> Ok , it's happening when we click over the newly made component section

Any solutions for it ?

**Comment by SurajPratap10** [comment]
> > Ok , it's happening when we click over the newly made component section
> 
> Any solutions for it ?

ya solved
<div id="footer" style="margin-top: 40rem;"></div> we have to add this in footer.html at the top

**Comment by SurajPratap10** [comment]
<div id="footer" style="margin-top: 40rem;"></div>

**Comment by siddhi-244** [comment]
Cool. Assigning you this!

**Comment by SurajPratap10** [comment]
> Cool. Assigning you this!

ok, do merge my PR as it may also show old commits when I generate a new PR for this issue

**Comment by SurajPratap10** [comment]
> > Cool. Assigning you this!
> 
> ok, do merge my old PR as it may also show old commits when I generate a new PR for this issue

**Comment by SurajPratap10** [comment]
@siddhi-244 seems Okay right? 

https://user-images.githubusercontent.com/92919173/217037178-a6ac98a7-5759-493c-8b4e-980cd6561a27.mp4

**Comment by siddhi-244** [comment]
> @siddhi-244 seems Okay right?
> 
>  Embellish.Mozilla.Firefox.2023-02-06.22-36-29.mp4

Looks awesome

**Comment by SurajPratap10** [comment]
> > @siddhi-244 seems Okay right?
> > Embellish.Mozilla.Firefox.2023-02-06.22-36-29.mp4
> 
> Looks awesome

ok doing

**Comment by SurajPratap10** [comment]
The bug is fixed now, I checked the live website

**Comment by siddhi-244** [comment]
There is alot of gap here which isn't looking good. If you can open a new issue and fix it 
![Screenshot_20230206-225817_Chrome](https://user-images.githubusercontent.com/69195262/217042205-e01b99b3-e573-4f08-a3c1-0c8b667f2e94.jpg)

**Comment by SurajPratap10** [comment]
![image](https://user-images.githubusercontent.com/92919173/217042179-3a14a400-ca74-421a-8d69-7a342907a660.png)
*This line of code was needed and I added that via commit*

**Comment by SurajPratap10** [comment]
> There is alot of gap here which isn't looking good. If you can open a new issue and fix it ![Screenshot_20230206-225817_Chrome](https://user-images.githubusercontent.com/69195262/217042205-e01b99b3-e573-4f08-a3c1-0c8b667f2e94.jpg)

Ok so the previous one was fixed right. for that I will open a new issue .

**Comment by siddhi-244** [comment]
> > There is alot of gap here which isn't looking good. If you can open a new issue and fix it ![Screenshot_20230206-225817_Chrome](https://user-images.githubusercontent.com/69195262/217042205-e01b99b3-e573-4f08-a3c1-0c8b667f2e94.jpg)
> 
> Ok so the previous one was fixed right. For this bug I will open a new issue after a while .

@SurajPratap10 any updates on this?
