### ISSUE TITLE
top margin of navbar section is huge

### ISSUE THREAD

**Issue by niladrix719** [siddhi-244/Embellish#367]
**Describe the bug**
top margin of navbar section is huge

**To Reproduce**
1. Go to 'https://embellish.netlify.app/'
2. Scroll down to 'Navbar'
3. See error.. Way to large margins

**Expected behavior**
margins should be smaller

**Screenshots**
![Screenshot from 2023-02-07 19-16-35](https://user-images.githubusercontent.com/91966855/217263346-b596dc86-0d4e-4936-ac44-9ad41b9901e1.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 22]
 - Browser [chrome]
 - Version [22]

**Comment by siddhi-244** [comment]
Cool
