### ISSUE TITLE
Bar Loader Animation

### ISSUE THREAD

**Issue by Nikhita28** [siddhi-244/Embellish#38]
**Is your feature request related to a problem? Please describe.**
No, it is not related to a problem.

**Describe the solution you'd like**
I would like to add a bar loader animation with a glow on the bars. It will be a good addition to the repository.

**Tech Stack to be used**
- HTML
- CSS

**Comment by siddhi-244** [comment]
Please follow issue template

**Comment by Nikhita28** [comment]
Updated, please check

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊🎊
