### ISSUE TITLE
Animated Glowing Button using HTML & CSS

### ISSUE THREAD

**Issue by arkayyy** [siddhi-244/Embellish#46]
**Is your feature request related to a problem? Please describe.**
Buttons components already provided with packages like material UI or Bootstrap are not animated and not fully customizable in that section.

**Describe the solution you'd like**
I would like to create a stylish glowing animated button using just HTML and CSS, which can be implemented in almost any project.

**Describe alternatives you've considered**
Buttons components in Material UI or Bootstrap.

**Additional context**
![wfkkwemfke](https://user-images.githubusercontent.com/72148786/135675294-648ce4fe-b7d0-4910-85b1-c407cce44dda.PNG)

![ekmkwmke](https://user-images.githubusercontent.com/72148786/135675320-8e7ec8e6-5188-4736-b22c-6025dd41f4ed.PNG)

**Comment by arkayyy** [comment]
@siddhi-244  Please do consider assigning this issue to me under tag of Hacktoberfest 2021.

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊

**Comment by siddhi-244** [comment]
Why you made 2 prs?

**Comment by arkayyy** [comment]
> Why you made 2 prs?

@siddhi-244 Actually I had to add 2 components. One is this current one 'animated glowing button' in 'Buttons' directory, and another one in the 'animated search bar' in the 'Search-Bar' directory. As you told me to update the main readme file, by mistake I created another PR for 'updating readme.md'. I am extremely sorry for the same as this is my first time at Hacktoberfest. Please do accept these two main PRs. Thank you!

**Comment by siddhi-244** [comment]
Delete both prs and make only 1 pr

**Comment by arkayyy** [comment]
@siddhi-244 I have deleted both PRs and created separate PRs for each. Do check it. Thanks
