### ISSUE TITLE
HTML and CSS-only carousel

### ISSUE THREAD

**Issue by ps4449** [siddhi-244/Embellish#47]
**Is your feature request related to a problem? Please describe.**
I wanted to incorporate carousel-like animation without JS.

**Describe the solution you'd like**
I'll be using HTML and CSS only, to create a carousel that will be compatible with most frameworks.

**Describe alternatives you've considered**
Using packages just as Vue or React.

**Additional context**
![image](https://user-images.githubusercontent.com/67458613/135676619-2950e067-1371-418b-9113-2e2bbb69b00e.png)

**Comment by siddhi-244** [comment]
Assigning this to you🎊🎊🎊🎊🎊
