### ISSUE TITLE
Add progress bars on scroll reveal

### ISSUE THREAD

**Issue by Asmit2952** [siddhi-244/Embellish#57]
**Is your feature request related to a problem? Please describe.**
Whenever user will scroll the screen, the progress bars will appear and when the user scrolls up back, the progress bar will disappear.

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** Whenever user will scroll the screen, the progress bars will appear and when the user scrolls up back, the progress bar will disappear.

Assigning it to you
