### ISSUE TITLE
fix: Add `hacktoberfest` label to the repo

### ISSUE THREAD

**Issue by guptasajal411** [siddhi-244/Embellish#6]
**Describe the bug**
I noticed that the repo is missing the `hacktoberfest` label. It would be more convenient for contributors to find this awesome repo if you add the label

**Screenshots**
![image](https://user-images.githubusercontent.com/70312106/135489153-e06198a8-2444-4be9-9c56-63c67fe51d4a.png)

**Additional context**
I'd love to add my cool components here after this bug is fixed. Thanks!

**Comment by siddhi-244** [comment]
> **Describe the bug** I noticed that the repo is missing the `hacktoberfest` label. It would be more convenient for contributors to find this awesome repo if you add the label
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/70312106/135489153-e06198a8-2444-4be9-9c56-63c67fe51d4a.png)
> 
> **Additional context** I'd love to add my cool components here after this bug is fixed. Thanks!

Hello I have added the label. You can start creating new issues from 1st Oct. Thank you !

**Comment by siddhi-244** [comment]
I am closing the issue for now but you can surely open new ones .
