### ISSUE TITLE
Add a modal

### ISSUE THREAD

**Issue by akkaraju-satvik** [siddhi-244/Embellish#61]
**Is your feature request related to a problem? Please describe.**
Most people depend face difficulty creating modal using just HTML, CSS and JS. 

**Describe the solution you'd like**
Clicking a button should open a modal.

**Comment by amandeep2326** [comment]
Pls assign this issue to me @akkaraju-satvik

**Comment by akkaraju-satvik** [comment]
> Pls assign this issue to me @akkaraju-satvik

I have already implemented this.
