### ISSUE TITLE
Add a card with some animation

### ISSUE THREAD

**Issue by viveena30** [siddhi-244/Embellish#64]
**Is your feature request related to a problem? Please describe.**
I want to add a card layout which is unique but the code remains as simple as it can.

**Describe the solution you'd like**
I'll be using HTML and CSS only, to create a card. 

**Describe alternatives you've considered**
Using react components is a better way to do this too

**Comment by siddhi-244** [comment]
We don't want React components for now

**Comment by viveena30** [comment]
no, i will be making it using HTML CSS only
