### ISSUE TITLE
Animated Social Media Links Component using HTML & CSS

### ISSUE THREAD

**Issue by arkayyy** [siddhi-244/Embellish#67]
**Is your feature request related to a problem? Please describe.**
Most of the sites contain static social media links as icons, but it doesn't add up to the elegance of the website.

**Describe the solution you'd like**
A customizable social media links component which is animated. On mouse hover on it, the icon would expand into a link.

**Describe alternatives you've considered**
Social media links section in Bootstrap and Material UI.

**Additional context**

![Screen-Recording-_02-10-2021-17-19-38_](https://user-images.githubusercontent.com/72148786/135714849-78459ff1-c9d2-49cf-a429-fc2111ee66e3.gif)

**Comment by arkayyy** [comment]
@siddhi-244 Please consider assigning this issue to me under Hacktoberfest 2021 tag. Thank you!

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊
