### ISSUE TITLE
Add typewriter text animation with blinker

### ISSUE THREAD

**Issue by NerdyVisky** [siddhi-244/Embellish#71]
## Aim 
To integrate the following feature under the 'Text Animations' directory

## Demo
![type-writer-demo](https://user-images.githubusercontent.com/77059453/135716437-7e807bb1-755e-4c29-b795-38ea379871da.gif)

## Note
- I will replace text content with neutral/filler content.
- I will enable easy modification to text content with well-commented code.
- I will abide by community guidelines and code of conduct

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊🎊🎊
