### ISSUE TITLE
Css text reveal animation

### ISSUE THREAD

**Issue by swapnil604** [siddhi-244/Embellish#74]
**Is your feature request related to a problem? Please describe.**
Animation for text reveal

**Describe the solution you'd like**
Reveal the text when user loads the page

**Comment by swapnil604** [comment]
@siddhi-244 kindly assign with relevant labels.

**Comment by siddhi-244** [comment]
Go for it🎊🎊🎊

**Comment by manishreddy6305** [comment]
Is your feature request related to a problem? Please describe.
It is not related to any problem

Describe the solution you'd like
I want to create a  text reveal animation using Html & CSS

Additional context:

https://user-images.githubusercontent.com/76482822/135969468-576a8968-3df4-436f-8706-0e334fec6eff.mp4

Can you assign this issue to me ?
