### ISSUE TITLE
CSS card hover effect

### ISSUE THREAD

**Issue by anshnarula5** [siddhi-244/Embellish#79]
**Is your feature request related to a problem? Please describe.**
A card hover effect.

**Describe the solution you'd like**
CSS based card component which shows its effect on hover

**Additional context**

Add any other context or screenshots about the feature request here
![CssHoverEffect](https://user-images.githubusercontent.com/66325953/135720596-7e94e78a-3204-4ad6-b5ef-d8e08cf41147.gif)
.

**Comment by anshnarula5** [comment]
@siddhi-244 Can you please assign this to me under hacktoberfest 2021 😀

**Comment by yadavashishdhirendra** [comment]
Hey, @siddhi-244 I have work on many Cards-Hover-Effects. u can also check my gitub-repo can you please assign this task to me so I can start working on ii!

**Comment by siddhi-244** [comment]
> @siddhi-244 Can you please assign this to me under hacktoberfest 2021 grinning

We need designed components! I see this is a bit plain.
