### ISSUE TITLE
Add Buttons

### ISSUE THREAD

**Issue by dro-1** [siddhi-244/Embellish#8]
**Is your feature request related to a problem? Please describe.**
I feel this repo would benefit from having button components also.

**Describe the solution you'd like**
A page containing button components

**Describe alternatives you've considered**
Nil

**Additional context**
Nil

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** I feel this repo would benefit from having button components also.
> 
> **Describe the solution you'd like** A page containing button components
> 
> **Describe alternatives you've considered** Nil
> 
> **Additional context** Nil

I will surely assign this issue to you tomorrow! As Hacktoberfest is starting from tomorrow.

**Comment by dro-1** [comment]
Alright then

**Comment by siddhi-244** [comment]
> Alright then

Surely I will assign this to you as soon as Hacktoberfest starts.

**Comment by siddhi-244** [comment]
Happy contributing 🎊🎊🤭
