### ISSUE TITLE
model component

### ISSUE THREAD

**Issue by AB-Jeet** [siddhi-244/Embellish#87]
**Describe the solution you'd like**
when page get loaded a model get pop up and ask user to enter details such as name , age etc

**Describe alternatives you've considered**
Modal component using HTML CSS and js

**Comment by AB-Jeet** [comment]
Pls assign me under the hactoberfest.

**Comment by yadavashishdhirendra** [comment]
Hey, @siddhi-244 I would like to work on this feature can u assign it to me.

**Comment by siddhi-244** [comment]
> Hey, @siddhi-244 I would like to work on this feature can u assign it to me.

You can make new issues

**Comment by siddhi-244** [comment]
> **Describe the solution you'd like** when page get loaded a model get pop up and ask user to enter details such as name , age etc
> 
> **Describe alternatives you've considered** Modal component using HTML CSS and js

We need designed components
