### ISSUE TITLE
Glassmorphism Card using HTML and CSS

### ISSUE THREAD

**Issue by itsme-aparna** [siddhi-244/Embellish#88]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
 I want to create a responsive and elegant glassmorphism card using only HTML and CSS.

**Picture of the component**
![glassmorphism](https://user-images.githubusercontent.com/57916734/135724553-3c8139a4-28c6-40a8-9dfc-26e8fc501ef5.jpeg)

**Comment by itsme-aparna** [comment]
@siddhi-244 please assign this to me under hacktoberfest 2021

**Comment by siddhi-244** [comment]
Assigning 🎊🎊🎊🎊🎊

**Comment by shrey802** [comment]
What should be included in this card??
