### ISSUE TITLE
Adding some more folders

### ISSUE THREAD

**Issue by honeykpatel** [siddhi-244/Embellish#9]
**Is your feature request related to a problem? Please describe.**
There isn't Folders for Button (someone had already mentioned) , scrollbars, some hover effects and text effects.

**Describe the solution you'd like**
So can I add them? I'm kinda new to front end and have some snippets so if I can add them here..

Thank you.

**Comment by siddhi-244** [comment]
> **Is your feature request related to a problem? Please describe.** There isn't Folders for Button (someone had already mentioned) , scrollbars, some hover effects and text effects.
> 
> **Describe the solution you'd like** So can I add them? I'm kinda new to front end and have some snippets so if I can add them here..
> 
> Thank you.

Hello. You need to add some components as well.

**Comment by honeykpatel** [comment]
Yes ofcourse,  Will add components like form and animations in respected folders. Or shall I just add them without folder

**Comment by siddhi-244** [comment]
> Yes ofcourse, Will add components like form and animations in respected folders. Or shall I just add them without folder

Create a new issue with description of component.
