### ISSUE TITLE
Animated Wave-based Footer Component using HTML & CSS

### ISSUE THREAD

**Issue by arkayyy** [siddhi-244/Embellish#91]
**Is your feature request related to a problem? Please describe.**
Footer components already provided with packages like material UI or Bootstrap are not animated and not fully customizable in that section.

**Describe the solution you'd like**
I would like to create an animated wave-like footer section using just HTML and CSS, which can be implemented in almost any project.

**Describe alternatives you've considered**
Footer components in Material UI or Bootstrap.

**Additional context**

![Screen-Recording-_02-10-2021-22-17-38_](https://user-images.githubusercontent.com/72148786/135725545-1d70cf2f-1952-4604-af2f-4c04fadf551e.gif)

**Comment by arkayyy** [comment]
@siddhi-244 Please do consider assigning this issue to me under the Hacktoberfest 2021 tag. Thanks.

**Comment by siddhi-244** [comment]
> @siddhi-244 Please do consider assigning this issue to me under the Hacktoberfest 2021 tag. Thanks.

Assigning it to you🎊🎊

**Comment by SumitKrShakya** [comment]
Pls assign me under the hacktoberfest.
