### ISSUE TITLE
Make a glassmorphism-based Contact form using HTML and CSS

### ISSUE THREAD

**Issue by itsme-aparna** [siddhi-244/Embellish#92]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I want to build a simple and elegant contact form using HTML and CSS 

**Additional context**
![WhatsApp Image 2021-10-02 at 10 49 29 PM (1)](https://user-images.githubusercontent.com/57916734/135726534-18df15c5-5a31-4d48-be9b-5133ff520a64.jpeg)

**Comment by itsme-aparna** [comment]
@siddhi-244 please assign this to me under hacktoberfest 2021

**Comment by siddhi-244** [comment]
Try something new
