### ISSUE TITLE
Multilevel footer component using HTML and CSS

### ISSUE THREAD

**Issue by NehaAnand28** [siddhi-244/Embellish#96]
**Is your feature request related to a problem? Please describe.**
A multilevel footer component

**Describe the solution you'd like**
I would like to create a multilevel footer component that provides links to different parts of a webpage with social icons.

**Additional context**
Similiar to this 
![footer](https://user-images.githubusercontent.com/70203777/135745342-dafb0a87-2ff3-4a44-a6a0-bae675441711.jpg)

**Comment by NehaAnand28** [comment]
@siddhi-244 please assign this to me under hacktoberfest 2021.

**Comment by SumitKrShakya** [comment]
can you please assign this to me under Hacktoberfest 2021.

**Comment by siddhi-244** [comment]
> @siddhi-244 please assign this to me under hacktoberfest 2021.

Assigning this to you🎊🎊🎊🎊
